version: '3.9'

services:

  db:
    image: postgres:latest
    restart: always
    shm_size: 128mb
    env_file:
      - ./config.env
    ports:
      - 5432:5432

  go-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - 8080:8080
    env_file:
      - ./config.env
    depends_on:
      - db